---
applications:
  - name: homevisit-accuservice
    memory: 1G
    disk_quota: 512M
    instances: 1
    timeout: 180
    hosts:
      - homevisit-accuservice
    path: ../build/libs/accuservice-0.0.1-SNAPSHOT.jar
    buildpack: java_buildpack_offline
    env:
      SPRING_PROFILES_ACTIVE: prod
    services:
      - dbcreds
      - config-server
      - config-server-keystore

